### ISSUE TITLE
Namespacify is cumbersome

### ISSUE THREAD

**Issue by NoahTheDuke** [zaaack/foy#13]
`namespacify` requires writing the namespace and task logic twice: first in the namespacify call and then in the actual namespace and task calls. I might as well just write them out as strings, bypassing the main benefit of using a function like `namespace`. It would be nice if the `namespacify` work happened without intervention: you call namespace, and then inside you call a task, and it joins them together for you.

**Comment by zaaack** [comment]
The namespace feature is updated in v0.2.0 via a more generally way, you can checkout the [docs](https://github.com/zaaack/foy#using-namespaces) or [tests](https://github.com/zaaack/foy/blob/master/src/test/fixtures/Foyfile2.ts)

**Comment by NoahTheDuke** [comment]
Looks like this can be closed then! Thank you!
