### ISSUE TITLE
Out of date types

### ISSUE THREAD

**Issue by NoahTheDuke** [zaaack/foy#14]
Hey hey!

Tried to use foy, but ran into issues with the typings. So I tried to build it locally, and found that it doesn't build at all for me. Looks like DefinitelyTyped has removed a bunch of package typings as they are now done in-house, and most of the typing packages you rely on aren't supported anymore: @types/node, @types/log-symbols, @types/log-update, @types/strip-ansi, @types/figures, @types/axios, @types/execa. And then it looks like you're using a bunch of outdated tools/libraries, which makes typings difficult (typedocs is on 0.19.1 now, for example).

Thanks!

**Comment by zaaack** [comment]
@NoahTheDuke I updated the deps and fixed some typing, you can try it at v0.2.1
