### ISSUE TITLE
[Question] Having trouble using foy

### ISSUE THREAD

**Issue by JUSTIVE** [zaaack/foy#22]
Hi, I'm trying to use this library, but I'm having trouble with it.
even with the basic example that Foy init gives, it does not work at all, which is

```javascript
const { task, desc, option, fs } = require('foy')

  task('build', async ctx => {
    await ctx.exec('echo "hello world"')
  })
```
and does not print at all. tried changing command to something simple, also does not work at all.
Am I missing something here?

for more information, I'm using node@20.

**Comment by zaaack** [comment]
@JUSTIVE Plz try this and run `npx foy build` again:

```ts
const { task, desc, option, fs,setGlobalOptions } = require('foy')
setGlobalOptions({ loading: false })
  task('build', async ctx => {
    await ctx.exec('echo "hello world"')
  })
```

**Comment by zaaack** [comment]
do you use windows？

**Comment by JUSTIVE** [comment]
> @JUSTIVE Plz try this and run `npx foy build` again:
> 
> ```ts
> const { task, desc, option, fs,setGlobalOptions } = require('foy')
> setGlobalOptions({ loading: false })
>   task('build', async ctx => {
>     await ctx.exec('echo "hello world"')
>   })
> ```

still same, without any stdout prints. I'm using mac(apple silicon).
tried on node, and also bun, same outputs.

**Comment by JUSTIVE** [comment]
figured out how it works. I had to pass another 'build' to execute properly. 
`bun ./index.ts build` was the solution I needed.
