### ISSUE TITLE
New task hierarchy feature causes duplicate console output

### ISSUE THREAD

**Issue by dominicporteous** [zaaack/foy#7]
If the height of the hierarchy 'tree' is greater than the height of the terminal it is being run in, then the whole tree will be re-written to the termnial on every tick of the spinner.

I guess this may be a problem with the spinner library rather than the foy implementation

**Comment by zaaack** [comment]
@dominicporteous Thanks for reporting, foy is using (log-update)[https://github.com/sindresorhus/log-update] to render the loading graph, and here actually is an issue about resizing terminal: https://github.com/sindresorhus/log-update/issues/36 It's a little tricky, let me see what we can do...

**Comment by zaaack** [comment]
@dominicporteous Fixed in v0.1.10!
